collections:
  hljomsveitir:
    output: true

defaults:
  - scope:
      path: ""
      type: "hljomsveitir"
    values:
      layout: "hljomsveit"
  - scope:
      path: ""
    values:
      layout: "default"